language: go

go:
  - 1.12.x
  - 1.x

before_install:
  - sudo apt-get -y install libopus-dev libopusfile-dev libpulse-dev
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - make build
  - make check
